ALTER TABLE sprints ADD COLUMN IF NOT EXISTS committed_points INT NOT NULL DEFAULT 0;
ALTER TABLE sprints ADD COLUMN IF NOT EXISTS committed_hours FLOAT NOT NULL DEFAULT 0;
ALTER TABLE sprints ADD COLUMN IF NOT EXISTS retrospective TEXT;
